### ISSUE TITLE
Empty Idle Queues

### ISSUE THREAD

**Issue by nini-os** [rudijs/amqp.node-rpc-factory#1]
Hi,

first of all: thank you for your work.

every time I create an RPC producer call (not standalone), after receiving the rpc it leaves an empy idle queue on rabbitmq. It's not so funny because for example after 400 requests it leaves 400 empty idle queues.

I suggest that you set "autoDelete: true" when creating the queue. 

Thank you

**Comment by rudijs** [comment]
Hi,

Just saw this issue, been busy working on other projects and didn't even notice it.

Apologies for that.

queueOptions is what you're needing I think. The readme has more details.

Here's the relevant snippet:

queueOptions : default: {exclusive: true} - AMQP options passed to the queue. You may find autoDelete: true useful in addition to exclusive if you wish the response queues cleaned up automatically.

**Comment by rudijs** [comment]
Hi,

I also just noticed this multiple idle connections problem in non-standalone mode.

In this case the problem is caused when there is no consumer of the RPC message.

Fixed and published here: https://github.com/rudijs/amqp.node-rpc-factory/commit/20a1e172791a0dc3918d116a32c9a87f84d244bc

**Comment by rudijs** [comment]
Hi @chiarishow 

Rpc producer autoDelete: true by default now: https://github.com/rudijs/amqp.node-rpc-factory/commit/938aac39aa606a9d204466bf5bf40b0a70d8a7bb

Thanks.

**Comment by nini-os** [comment]
Thank you really much!
