### ISSUE TITLE
publisher in the server example cannot create multiple reply queues

### ISSUE THREAD

**Issue by davidolen** [rudijs/amqp.node-rpc-factory#5]
When publish two requests, two exclusive reply queues should be asserted so that multiple consumers can be supported. However, currently a new reply queue can only be created after the previous reply queue has been deleted. This introduces a bottleneck for web apps.

**Comment by rudijs** [comment]
Hey David,

I see. Which example are you referring to? The ExpressJS or KoaJS example?

> When publish two requests, two exclusive reply queues should be asserted so that multiple consumers can be supported

Each request, client.publish(),  gets it's own exclusive reply queue.

Multiple consumers can listen on the same queue.

> currently a new reply queue can only be created after the previous reply queue has been deleted.

I haven't used this module outside the scope of how the two examples show.

Would you be able to provide some sample code that I could use to build a server example that replicates the bottleneck?

Seems odd and of course not ideal to have to wait for one reply queue to be removed before another can be created.

I'm happy to follow up on this, but if you could help with some code to show how you are using the code that would be great.

Thanks.

**Comment by davidolen** [comment]
Hi Rudi,

Thank you for your response. Please see below for the steps to reproduce.
It seems that the publish function cannot be executed concurrently in the context of express server.

Thank you!

David

Steps to Reproduce:

Step 1: start the local rabbitmq-service
Step 2: cd to examples\commandline\advanced-jsonrpc\
Step 3: modify the rpcMethodTable object in process-message.js so that it will take a noticable time to process
             var rpcMethodTable = {

```
              upcase: function (request) {

                //logic added for this test 
                var n = 1000000000, inside = 0, i, x, y;
                for ( i = 0; i < n; i++ ) {
                    x = Math.random();
                    y = Math.random();
                    if ( Math.sqrt(x * x + y * y) <= 1 )
                        inside++;
                }  

                return JSON.stringify({
                  jsonrpc: '2.0',
                  result: request.params.toUpperCase(),
                  id: request.id
                });
              }

        };
```

Step 4: start 2 instances of the rpc-json consumers (in two consoles, type: node rpc-consumer.js)
Step 5: cd to examples\server\expressjs\lib\
Step 6: increase the reply timeout value in rpc-publisher.js. For example as follows:
        if (!publisher) {
          publisher = rpcPublisherFactory.create({
            url: process.env.RABBITMQ_URL || 'localhost';

```
        //adjust the value based on your local environment
        replyTimeOutInterval: 60000;  
      });
    }
```

Step 7: cd to examples\server\expressjs\
Step 8: start the express server: node server.js

Step 9: start 2 browser windows,  and in each browser open the url "http://localhost:8080/api/upcase/hello".
       (try to open both urls at the same time)

Step 10: observe that the queues in rabbitmq.

Expected: there should be three queues: node_rpc_queue, and 2 reply queues
Actual: there are only two queues: node_rpc_queue, and only 1 reply queue

Note: this seems not an issue when publishing messages using the command line publishers.

**Comment by rudijs** [comment]
David,

OK cool, thanks for the detailed steps - makes following up so much easier.

I've stepped through the 10 steps you've listed.

Seems I actually get the expected results - 3 queues.

I've run it a couple times using Chrome browswer (two tabs) and also two differnet browsers (Chrome and Firefox).

Here's a series of screen caps starting with the connections (consumer and publisher) followed by the 3 queues appearing and disappearing in correct order:

![1](https://cloud.githubusercontent.com/assets/1711940/9296640/fb92a492-44c3-11e5-94f5-e91b514cee30.png)

![2](https://cloud.githubusercontent.com/assets/1711940/9296643/00fbdb42-44c4-11e5-9a1d-5b567aee5f6e.png)

![3](https://cloud.githubusercontent.com/assets/1711940/9296646/07b720d6-44c4-11e5-895d-ff323aa3cc93.png)

![4](https://cloud.githubusercontent.com/assets/1711940/9296648/0cb56f3e-44c4-11e5-9b2b-fa6f480719f3.png)

![5](https://cloud.githubusercontent.com/assets/1711940/9296651/109808be-44c4-11e5-9b21-88a69409b277.png)

![6](https://cloud.githubusercontent.com/assets/1711940/9296652/1589cf42-44c4-11e5-8114-fc53c46748db.png)

**Comment by davidolen** [comment]
Thank you Rudi, I finally figured it out.
The issue is with the firefox browser: When the same url request (e.g., http://localhost:8080/api/upcase/hello) is sent from two different firefox windows (or tabs), firefox will queue them and send the 2nd request only after the 1st request has finished. 
When I send one request in firefox and the other in chrome (or ie), I do get the expected results (two reply queues have been created).  One thing I noticed is that chrome tries to send the same request twice. I think this is most likely due to chrome's advanced prediction features.

By the way, I got two more questions. If possible, could you please take a look?

1) My understanding is that in the node.js world, using a message queue to decouple (delegate) computational expensive tasks so far is still considered one of the most scalable and feasible approaches. Am I right?

2) In rpc-publisher-factory.js and rpc-consumer-factory.js, you have wrapped the entire publisher and consumer functionalities inside their prototype objects, which are later called by Object.create(). Normally, prototype objects are shared among instances. So, in the server example, if a single publisher information (including its connection information) is always shared through its prototype, how can two reply queues be created concurrently?

Thank you!

**Comment by rudijs** [comment]
Hey David,

OK cool, glad that's all sorted then.

It's a good exercise for me too, I wasn't sure 100% myself of the behavior you described so working through it with you help me out too.

> My understanding is that in the node.js world, using a message queue to decouple (delegate) computational expensive tasks so far is still considered one of the most scalable and feasible approaches. Am I right?

Well I'm no guru but I think the approach of using a message queue to decouple the computational expense is scalable and feasable for all languages - not just node.

It does add some complexity and more points of failure but ultimately going distributed is the only way to scale.

Feasable? Well the price is right - Free :-) Just spin up more VMs to handle the load will be your cost.

> how can two reply queues be created concurrently?

the publish() method returns a promise so you can use q.all() with an array of promises for concurrent execution.

Check out the q docs: https://github.com/kriskowal/q/wiki/API-Reference

```
promise.all()

Returns a promise that is fulfilled with an array containing the fulfillment value of each promise, or is rejected with the same rejection reason as the first promise to be rejected.

This method is often used in its static form on arrays of promises, in order to execute a number of operations concurrently and be notified when they all succeed. For example:

Q.all([getFromDisk(), getFromCloud()]).done(function (values) {
    assert(values[0] === values[1]); // values[0] is fromDisk and values[1] is fromCloud
});
```

So you'd do something like (returns an array of two results):

```
function twoConcurrentMessages() {

  return q.all([client.publish('message 1'), client.publish('message2')])
    .then(function (res) {
      return res;
    })
    .catch(function (err) {
      return err;
    });
}
```

**Comment by rudijs** [comment]
Pro Tip: You should, or might like to, check out Derrick Baily's free 7 day email course on Rabbitmq patterns.

http://derickbailey.com/email-courses/rabbitmq-patterns-for-applications/

**Comment by davidolen** [comment]
These are great points! Thank you very much!
